---
- name: Configuración Común para Nodos Docker
  hosts: all
  become: yes # La mayoría de las tareas requieren privilegios de root
  vars:
    repo_url: https://github.com/tecducatio/bus-app.git
    repo_dest: /vagrant/bus-app # Destino dentro del invitado (corresponde a ./bus-app en el host)
    app_build_dir: "{{ repo_dest }}/bus-ticket-app/" # Directorio para build/deploy
  tasks:
    - name: Actualizar caché de apt
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Actualizar solo si la caché tiene más de 1 hora. La IA optimiza cosas

    - name: Instalar paquetes prerrequisito (incluyendo git)
      ansible.builtin.apt:
        # Asegurarse de que git está instalado para el módulo ansible.builtin.git
        name: ['curl', 'ca-certificates', 'gnupg', 'lsb-release', 'git']
        state: present


    - name: Comprobar si existe el script get-docker.sh
      ansible.builtin.stat:
        path: /tmp/get-docker.sh
      register: docker_script_stat

    - name: Descargar script get-docker.sh
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'
      when: not docker_script_stat.stat.exists

    - name: Ejecutar get-docker.sh para instalar Docker
      ansible.builtin.command:
        cmd: sh /tmp/get-docker.sh
        creates: /usr/bin/docker # Evita re-ejecutar si docker ya está instalado
      changed_when: true # Asumimos que siempre cambia el estado por simplicidad aquí

    - name: Añadir usuario vagrant al grupo docker
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: yes
      notify: Reiniciar Servicio Docker # Notifica al handler para reiniciar potencialmente docker

    - name: Asegurar que el servicio Docker está iniciado y habilitado
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes


  handlers:
    - name: Reiniciar Servicio Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
      listen: "Reiniciar Servicio Docker" # Nombra el listener (receptor de la notificación)
